[project]
name = "aerobenchvvpython"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "control",
    "matplotlib",
    "numpy",
    "onnxruntime>=1.22.0",
    "scipy",
]
